
- name: "HIGH | RHEL-07-010270 | PATCH | The SSH daemon must not allow authentication using
an empty password."
  hosts: all
  tasks:
    - lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: ^#?PermitEmptyPasswords
        line: PermitEmptyPasswords no
        validate: sshd -tf %s
      notify: restart sshd
    - sysctl:
        name: kernel.randomize_va_space
        value: "2"
        state: present
        reload: yes
        ignoreerrors: yes
      notify: reboot system
  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
    - name: reboot system
      reboot:
